/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospitalapp;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author David
 */
public class StocksGUI extends javax.swing.JFrame {
    
    private ArrayList <Medicine> sList;
    private double tablets;
    private double capsules;
    private double saline;
    private int count;
    
   

    /**
     * Creates new form StocksGUI
     */
    public StocksGUI() {
        initComponents();
        sList = new ArrayList <>();
        tablets = 0.0;
        capsules = 0.0;
        saline = 0.0;
        count = 0;
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        tabletsTf = new javax.swing.JTextField();
        capsulsTf = new javax.swing.JTextField();
        salineTf = new javax.swing.JTextField();
        medLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        medsList = new javax.swing.JList<>();
        covidTf = new javax.swing.JTextField();
        polioTf = new javax.swing.JTextField();
        fluTf = new javax.swing.JTextField();
        vacccineTable = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        vacList = new javax.swing.JList<>();
        dengueTf = new javax.swing.JTextField();
        vaccineLbl = new javax.swing.JLabel();
        equipmentTable = new javax.swing.JRadioButton();
        equipLbl = new javax.swing.JLabel();
        bandagesTf = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        equipList = new javax.swing.JList<>();
        gauzeTf = new javax.swing.JTextField();
        syringesTf = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        viewBtn = new javax.swing.JButton();
        menu2Btn = new javax.swing.JButton();
        ppeTf = new javax.swing.JTextField();
        headLbl = new javax.swing.JLabel();
        hospitalLbl = new javax.swing.JLabel();
        hospitalLbl1 = new javax.swing.JLabel();

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setBackground(new java.awt.Color(255, 0, 0));
        jLayeredPane1.setOpaque(true);

        tabletsTf.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tabletsTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabletsTfActionPerformed(evt);
            }
        });

        capsulsTf.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        capsulsTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capsulsTfActionPerformed(evt);
            }
        });

        salineTf.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        medLbl.setBackground(new java.awt.Color(255, 255, 255));
        medLbl.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        medLbl.setText("Medicine:");

        medsList.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        medsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Tablets:", "Capsuls:", "Saline:" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(medsList);

        covidTf.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        polioTf.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        fluTf.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        vacccineTable.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        vacccineTable.setText("View Vaccine Table");

        vacList.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        vacList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Covid 19:", "Polio:", "Flu:", "Dengue:" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(vacList);

        dengueTf.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        vaccineLbl.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        vaccineLbl.setText("Vaccine:");

        equipmentTable.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        equipmentTable.setText("View Equipment Table");

        equipLbl.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        equipLbl.setText("Equipment:");

        bandagesTf.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        equipList.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        equipList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "PPE:", "Bandages:", "Gauze:", "Syringes:" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(equipList);

        gauzeTf.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        syringesTf.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        addBtn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        viewBtn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        viewBtn.setText("View");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });

        menu2Btn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        menu2Btn.setText("Menu");
        menu2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu2BtnActionPerformed(evt);
            }
        });

        ppeTf.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        headLbl.setFont(new java.awt.Font("Viner Hand ITC", 1, 20)); // NOI18N
        headLbl.setText("Stocks");

        hospitalLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalapp/icon.png"))); // NOI18N

        hospitalLbl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalapp/icon.png"))); // NOI18N

        jLayeredPane1.setLayer(tabletsTf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(capsulsTf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(salineTf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(medLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(covidTf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(polioTf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(fluTf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(vacccineTable, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(dengueTf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(vaccineLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(equipmentTable, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(equipLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(bandagesTf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(gauzeTf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(syringesTf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(addBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(viewBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(menu2Btn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(ppeTf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(headLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(hospitalLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(hospitalLbl1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(hospitalLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(headLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(hospitalLbl1))
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tabletsTf, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(salineTf, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(capsulsTf, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(polioTf, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fluTf, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dengueTf, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(covidTf, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(equipLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vaccineLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bandagesTf, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ppeTf, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gauzeTf, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(syringesTf, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vacccineTable, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(equipmentTable, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(addBtn)
                        .addGap(18, 18, 18)
                        .addComponent(viewBtn)
                        .addGap(18, 18, 18)
                        .addComponent(menu2Btn))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(medLbl)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(headLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(hospitalLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hospitalLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(medLbl)
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(tabletsTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(capsulsTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(salineTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(vaccineLbl)
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(covidTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vacccineTable))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(polioTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(fluTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dengueTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(equipLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                        .addComponent(ppeTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bandagesTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(gauzeTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(syringesTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(equipmentTable)
                                .addGap(161, 161, 161)))
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(menu2Btn)
                            .addComponent(viewBtn)
                            .addComponent(addBtn))
                        .addGap(37, 37, 37))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(181, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(186, 186, 186))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void capsulsTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capsulsTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_capsulsTfActionPerformed

    private void menu2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu2BtnActionPerformed
        // TODO add your handling code here:
        MenuGUI myGUI = new MenuGUI();
        myGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menu2BtnActionPerformed

    private void tabletsTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabletsTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tabletsTfActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        
        tablets = Double.parseDouble(tabletsTf.getText());
        capsules = Double.parseDouble(capsulsTf.getText());
        saline = Double.parseDouble(salineTf.getText());
        
        Medicine a = new Medicine();
        
        // File Input and Output part for the add BTN//
        File outFile;
        FileWriter fw;
        BufferedWriter bw;

        String one = tabletsTf.getText();
        try {
            outFile = new File("stocks.txt");
            fw = new FileWriter(outFile, true);
            bw = new BufferedWriter(fw);

            bw.write(one);
            bw.newLine();

            bw.close();
            JOptionPane.showMessageDialog(null, "Numbers For Stocks HAve Been Sucessfully Updated Thank You");
        } catch (IOException e) {
            System.out.println("Sorry There Has been An Issue Here" + e);
        }

    }//GEN-LAST:event_addBtnActionPerformed

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        // TODO add your handling code here:
        String one;
        File inFile;
        FileReader fr;
        BufferedReader br;

        try {
            inFile = new File("stocks.txt");
            fr = new FileReader(inFile);
            br = new BufferedReader(fr);

            one = br.readLine();
            while (one != null) {
                JOptionPane.showMessageDialog(null, "Tablets Levels " + one);
                one = br.readLine();
            }
            br.close();

        } catch (IOException e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_viewBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StocksGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StocksGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StocksGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StocksGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StocksGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField bandagesTf;
    private javax.swing.JTextField capsulsTf;
    private javax.swing.JTextField covidTf;
    private javax.swing.JTextField dengueTf;
    private javax.swing.JLabel equipLbl;
    private javax.swing.JList<String> equipList;
    private javax.swing.JRadioButton equipmentTable;
    private javax.swing.JTextField fluTf;
    private javax.swing.JTextField gauzeTf;
    private javax.swing.JLabel headLbl;
    private javax.swing.JLabel hospitalLbl;
    private javax.swing.JLabel hospitalLbl1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel medLbl;
    private javax.swing.JList<String> medsList;
    private javax.swing.JButton menu2Btn;
    private javax.swing.JTextField polioTf;
    private javax.swing.JTextField ppeTf;
    private javax.swing.JTextField salineTf;
    private javax.swing.JTextField syringesTf;
    private javax.swing.JTextField tabletsTf;
    private javax.swing.JList<String> vacList;
    private javax.swing.JRadioButton vacccineTable;
    private javax.swing.JLabel vaccineLbl;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables
}
